//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KOSkillImporter.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KOSkillImporter.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE [dbo].[MAGIC_TYPE1_NEW](
        ///	[iNum] [int] NOT NULL,
        ///	[Name] [char](100) NULL,
        ///	[Description] [char](200) NULL,
        ///	[Type] [tinyint] NOT NULL,
        ///	[HitRate] [smallint] NOT NULL,
        ///	[Hit] [smallint] NOT NULL,
        ///	[AddDamage] [smallint] NOT NULL,
        ///	[Delay] [tinyint] NOT NULL,
        ///	[ComboType] [tinyint] NOT NULL,
        ///	[ComboCount] [tinyint] NOT NULL,
        ///	[ComboDamage] [smallint] NOT NULL,
        ///	[Range] [smallint] NOT NULL
        ///) ON [PRIMARY].
        /// </summary>
        internal static string Queries_CreateMagic1New {
            get {
                return ResourceManager.GetString("Queries_CreateMagic1New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE [dbo].[MAGIC_TYPE2_NEW](
        ///	[iNum] [int] NOT NULL,
        ///	[Name] [char](100) NOT NULL,
        ///	[Description] [char](200) NULL,
        ///	[HitType] [tinyint] NOT NULL,
        ///	[HitRate] [smallint] NOT NULL,
        ///	[AddDamage] [smallint] NOT NULL,
        ///	[AddRange] [smallint] NOT NULL,
        ///	[NeedArrow] [tinyint] NOT NULL,
        ///	[AddDamagePlus] [smallint] NULL
        ///) ON [PRIMARY].
        /// </summary>
        internal static string Queries_CreateMagic2New {
            get {
                return ResourceManager.GetString("Queries_CreateMagic2New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE [dbo].[MAGIC_TYPE3_NEW](
        ///	[iNum] [int] NOT NULL,
        ///	[Name] [char](100) NULL,
        ///	[Description] [char](200) NULL,
        ///	[Radius] [tinyint] NOT NULL,
        ///	[Angle] [smallint] NOT NULL,
        ///	[DirectType] [tinyint] NOT NULL,
        ///	[FirstDamage] [smallint] NOT NULL,
        ///	[EndDamage] [smallint] NOT NULL,
        ///	[TimeDamage] [smallint] NOT NULL,
        ///	[Duration] [tinyint] NOT NULL,
        ///	[Attribute] [tinyint] NOT NULL
        ///) ON [PRIMARY].
        /// </summary>
        internal static string Queries_CreateMagic3New {
            get {
                return ResourceManager.GetString("Queries_CreateMagic3New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE [dbo].[MAGIC_TYPE4_NEW](
        ///	[iNum] [int] NOT NULL,
        ///	[Name] [char](100) NOT NULL,
        ///	[Description] [char](200) NULL,
        ///	[BuffType] [tinyint] NOT NULL,
        ///	[Radius] [tinyint] NOT NULL,
        ///	[Duration] [smallint] NOT NULL,
        ///	[AttackSpeed] [tinyint] NOT NULL,
        ///	[Speed] [tinyint] NOT NULL,
        ///	[AC] [smallint] NOT NULL,
        ///	[ACPct] [smallint] NOT NULL,
        ///	[Attack] [tinyint] NOT NULL,
        ///	[MagicAttack] [tinyint] NOT NULL,
        ///	[MaxHP] [smallint] NOT NULL,
        ///	[MaxHpPct] [smallint] NOT NULL,
        ///	[MaxMP] [smallint] NOT NULL [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Queries_CreateMagic4New {
            get {
                return ResourceManager.GetString("Queries_CreateMagic4New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE [dbo].[MAGIC_TYPE5_NEW](
        ///	[iNum] [int] NOT NULL,
        ///	[Name] [char](100) NULL,
        ///	[Description] [char](200) NULL,
        ///	[Type] [tinyint] NOT NULL,
        ///	[ExpRecover] [tinyint] NOT NULL,
        ///	[NeedStone] [smallint] NOT NULL
        ///) ON [PRIMARY].
        /// </summary>
        internal static string Queries_CreateMagic5New {
            get {
                return ResourceManager.GetString("Queries_CreateMagic5New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE [dbo].[MAGIC_TYPE6_NEW](
        ///	[iNum] [int] NOT NULL,
        ///	[Name] [char](100) NOT NULL,
        ///	[Description] [char](200) NULL,
        ///	[Size] [smallint] NOT NULL,
        ///	[TransformID] [smallint] NOT NULL,
        ///	[Duration] [smallint] NOT NULL,
        ///	[MaxHp] [smallint] NOT NULL,
        ///	[MaxMp] [smallint] NOT NULL,
        ///	[Speed] [tinyint] NOT NULL,
        ///	[AttackSpeed] [smallint] NOT NULL,
        ///	[TotalHit] [smallint] NOT NULL,
        ///	[TotalAc] [smallint] NOT NULL,
        ///	[TotalHitRate] [smallint] NOT NULL,
        ///	[TotalEvasionRate] [smallint] NOT NULL,
        ///	[Tota [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Queries_CreateMagic6New {
            get {
                return ResourceManager.GetString("Queries_CreateMagic6New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE [dbo].[MAGIC_TYPE9_NEW](
        ///	[iNum] [int] NOT NULL,
        ///	[Name] [char](30) NULL,
        ///	[Description] [char](100) NULL,
        ///	[ValidGroup] [tinyint] NOT NULL,
        ///	[NationChange] [tinyint] NOT NULL,
        ///	[MonsterNum] [smallint] NOT NULL,
        ///	[TargetChange] [tinyint] NOT NULL,
        ///	[StateChange] [tinyint] NOT NULL,
        ///	[Radius] [smallint] NOT NULL,
        ///	[Hitrate] [smallint] NOT NULL,
        ///	[Duration] [smallint] NOT NULL,
        ///	[AddDamage] [smallint] NOT NULL,
        ///	[Vision] [smallint] NOT NULL,
        ///	[NeedItem] [int] NOT NULL
        ///) ON [PRIMARY [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Queries_CreateMagic9New {
            get {
                return ResourceManager.GetString("Queries_CreateMagic9New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE [dbo].[MAGIC_NEW](
        ///	[MagicNum] [int] NOT NULL,
        ///	[EnName] [char](100) NULL,
        ///	[KrName] [char](100) NULL,
        ///	[Description] [char](200) NULL,
        ///	[BeforeAction] [tinyint] NOT NULL,
        ///	[TargetAction] [tinyint] NOT NULL,
        ///	[SelfEffect] [tinyint] NOT NULL,
        ///	[FlyingEffect] [smallint] NOT NULL,
        ///	[TargetEffect] [smallint] NOT NULL,
        ///	[Moral] [tinyint] NOT NULL,
        ///	[SkillLevel] [smallint] NOT NULL,
        ///	[Skill] [smallint] NOT NULL,
        ///	[Msp] [smallint] NOT NULL,
        ///	[HP] [smallint] NOT NULL,
        ///	[ItemGroup] [tinyi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Queries_CreateMagicNew {
            get {
                return ResourceManager.GetString("Queries_CreateMagicNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IF EXISTS (SELECT * FROM sysobjects WHERE id = object_id(N&apos;[dbo].[MAGIC_NEW]&apos;) AND OBJECTPROPERTY(id, N&apos;IsUserTable&apos;) = 1)
        ///DROP TABLE [dbo].[MAGIC_NEW]
        ///IF EXISTS (SELECT * FROM sysobjects WHERE id = object_id(N&apos;[dbo].[MAGIC_TYPE1_NEW]&apos;) AND OBJECTPROPERTY(id, N&apos;IsUserTable&apos;) = 1)
        ///DROP TABLE [dbo].[MAGIC_TYPE1_NEW]
        ///IF EXISTS (SELECT * FROM sysobjects WHERE id = object_id(N&apos;[dbo].[MAGIC_TYPE2_NEW]&apos;) AND OBJECTPROPERTY(id, N&apos;IsUserTable&apos;) = 1)
        ///DROP TABLE [dbo].[MAGIC_TYPE2_NEW]
        ///IF EXISTS (SELECT * FROM s [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Queries_DropAllNew {
            get {
                return ResourceManager.GetString("Queries_DropAllNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sp_rename @OldName,@NewName.
        /// </summary>
        internal static string Queries_RenameTable {
            get {
                return ResourceManager.GetString("Queries_RenameTable", resourceCulture);
            }
        }
    }
}
